#!/usr/bin/env ruby
# frozen_string_literal: true

versions = []
inline_code = []
ruby_flags = []
save_path = nil
args = ARGV.dup
while args.first
  case args.first
  when "--ruby"
    args.shift
    versions << args.shift
  when "-e"
    args.shift
    inline_code << args.shift
  when "-r"
    args.shift
    ruby_flags.push("-r", args.shift)
  when "--disable-gems", /\A--yjit/, /\A--zjit/
    ruby_flags << args.shift
  when "--save"
    args.shift
    save_path = args.shift
  when "-v", "--verbose"
    args.shift
    verbose = true
  when /\A-/
    $stderr.puts "Unknown option: #{args.first}"
    exit 1
  else
    break
  end
end
script = args.shift

if script.nil? && inline_code.empty?
  $stderr.puts "Usage: ips [--ruby VERSION ...] [-e CODE ...] [<script>]"
  exit 1
end

if inline_code.any?
  run_opts = versions.size > 1 ? "(summary: false)" : ""
  script_source = +"require 'ips'\nresult = IPS.run#{run_opts} do |x|\n"
  inline_code.each do |code|
    script_source << "  x.report(#{code.inspect}, #{code.inspect})\n"
  end
  script_source << "end\n"
  script_source << "IO.open(3, 'w') { |f| Marshal.dump(result, f) }\n"
  ruby_args = ["-e", script_source]
else
  ruby_args = [script]
end

# Shell-escape for display purposes only, not for security.
def shell_quote(arg)
  return arg if arg =~ /\A[A-Za-z0-9_\-.,:+\/@]+\z/
  "'" + arg.gsub("'", "'\\\\''") + "'"
end

RUBY_DIRS = [File.expand_path("~/.rubies"), "/opt/rubies"]
LIB_DIR = File.expand_path("../lib", __dir__)

def find_ruby(version)
  RUBY_DIRS.each do |dir|
    next unless Dir.exist?(dir)
    Dir.children(dir).sort.each do |name|
      bare = name.delete_prefix("ruby-")
      if bare.start_with?(version)
        ruby = File.join(dir, name, "bin", "ruby")
        return ruby if File.executable?(ruby)
      end
    end
  end
  nil
end

def resolve_ruby(str)
  version, *extra_flags = str.split
  if File.executable?(version)
    ruby = version
  else
    ruby = find_ruby(version) or abort "No ruby found matching #{version.inspect}"
  end
  [ruby, extra_flags]
end

if versions.empty?
  rubies = [[nil, []]]
else
  rubies = versions.map { |v| resolve_ruby(v) }
end

$LOAD_PATH.unshift(LIB_DIR)
require "ips"

results = []

rubies.each do |ruby, extra_flags|
  if ruby
    env = { "GEM_HOME" => nil, "GEM_PATH" => nil }
  else
    ruby = "ruby"
    env = {}
  end

  cmd = [ruby, *extra_flags, *ruby_flags, "-v", "-I", LIB_DIR, *ruby_args]
  $stderr.puts cmd.map { |a| shell_quote(a) }.join(" ") if verbose

  rd, wr = IO.pipe
  pid = spawn(env, *cmd, 3 => wr)
  wr.close
  data = rd.read
  rd.close
  Process.wait(pid)
  raise "Child process failed" unless $?.success?
  results << Marshal.load(data) unless data.empty?
  puts
end

IPS::Result.compare(results)

if save_path && results.any?
  IPS::Result.save!(save_path, results)
end
