#!/usr/bin/env ruby
# frozen_string_literal: true

versions = []
inline_code = []
args = ARGV.dup
while args.first
  case args.first
  when "--ruby"
    args.shift
    versions << args.shift
  when "-e"
    args.shift
    inline_code << args.shift
  else
    break
  end
end
script = args.shift

if script.nil? && inline_code.empty?
  $stderr.puts "Usage: ips [--ruby VERSION ...] [-e CODE ...] [<script>]"
  exit 1
end

if inline_code.any?
  script_source = +"require 'ips'\nIPS.run do |x|\n"
  inline_code.each do |code|
    script_source << "  x.report(#{code.inspect}, #{code.inspect})\n"
  end
  script_source << "end\n"
  ruby_args = ["-e", script_source]
else
  ruby_args = [script]
end

if versions.empty?
  exec("ruby", "-I#{File.expand_path("../lib", __dir__)}", *ruby_args)
end

RUBY_DIRS = [File.expand_path("~/.rubies"), "/opt/rubies"]
LIB_DIR = File.expand_path("../lib", __dir__)

def find_ruby(version)
  RUBY_DIRS.each do |dir|
    next unless Dir.exist?(dir)
    Dir.children(dir).sort.each do |name|
      bare = name.delete_prefix("ruby-")
      if bare.start_with?(version)
        ruby = File.join(dir, name, "bin", "ruby")
        return [name, ruby] if File.executable?(ruby)
      end
    end
  end
  nil
end

versions.each do |version|
  result = find_ruby(version)
  if result.nil?
    $stderr.puts "No ruby found matching #{version.inspect}"
    exit 1
  end

  _name, ruby = result

  env = { "GEM_HOME" => nil, "GEM_PATH" => nil }
  system(env, ruby, "-v", "-I", LIB_DIR, *ruby_args, exception: true)
  puts
end
